### ISSUE TITLE
Blog Search Improvements

### ISSUE THREAD

**Issue by justinschmitz97** [justinschmitz97/avif.io#52]
**Tasks**
- [ ] Only use Post.tsx to show Blog Posts (currently using Post.tsx and Posts.tsx, based on if a filter is active)
- [ ] When no search is active, divide blog posts by their category
- [ ] If a search is active, still divide blog posts by their category
- [ ] When clicking on a filter button (eg. tutorials), the headline should be hidden

**Reference**
![image](https://user-images.githubusercontent.com/68192785/136106883-9c608185-b15e-434d-ab26-ee9ea66febc0.png)
